export const pages = {
  TOP: "/",
  COMPONENTS: {
    INDEX: "/components",
    ALERT: "/components/alert",
    AVATAR: "/components/avatar",
    BADGE: "/components/badge",
    BREADCRUMBS: "/components/breadcrumbs",
    BUTTON: "/components/button",
    CARD: "/components/card",
    CHECKBOX: "/components/checkbox",
    COLLAPSE: "/components/collapse",
    DIVIDER: "/components/divider",
    DROPDOWN: "/components/dropdown",
    FILE_INPUT: "/components/file-input",
    FORM_FIELD: "/components/form-field",
    INPUT: "/components/input",
    JOIN: "/components/join",
    KBD: "/components/kbd",
    LOADING: "/components/loading",
    MENU: "/components/menu",
    MODAL: "/components/modal",
    NAVBAR: "/components/navbar",
    PROGRESS: "/components/progress",
    RADIO: "/components/radio",
    RANGE: "/components/range",
    SELECT: "/components/select",
    SKELETON: "/components/skeleton",
    STAT: "/components/stat",
    STEPS: "/components/steps",
    TABLE: "/components/table",
    TABS: "/components/tabs",
    TEXTAREA: "/components/textarea",
    TOGGLE: "/components/toggle",
    TOOLTIP: "/components/tooltip",
  },
} as const;
